# Generated by Django 3.0.5 on 2020-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20200505_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateField(default='2020-05-06'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2020-05-06'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2020-05-06'),
        ),
    ]
