# Generated by Django 3.0.7 on 2020-06-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_auto_20200615_1848'),
        ('drive', '0006_user_profile_picture'),
    ]

    operations = [
    ]
