# Generated by Django 3.0.7 on 2020-06-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_auto_20200621_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.Carpeta'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='padre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.Carpeta'),
        ),
        migrations.AlterUniqueTogether(
            name='archivo',
            unique_together={('nombre', 'formato', 'usuario', 'carpeta')},
        ),
    ]
