# Generated by Django 3.0.7 on 2020-06-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_auto_20200624_2211'),
        ('drive', '0012_auto_20200624_2147'),
        ('drive', '0012_auto_20200624_2030'),
    ]

    operations = [
    ]
