# Generated by Django 3.0.7 on 2020-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_merge_20200626_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='tagstest',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='fecha_upload',
            field=models.DateField(default='2020-06-26'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateField(default='2020-06-26'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2020-06-26'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2020-06-26'),
        ),
    ]
