# Generated by Django 3.0.7 on 2020-06-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0014_auto_20200626_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='tagstest',
        ),
    ]
