# Generated by Django 3.0.7 on 2020-07-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_auto_20200715_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_upload',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2020-07-17'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2020-07-17'),
        ),
    ]
