# Generated by Django 3.0.7 on 2020-07-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0017_auto_20200716_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_upload',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='fecha_creacion',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2020-07-19'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2020-07-19'),
        ),
    ]
